[package]
name = "rustic_raymarch"
version = "0.1.0"
authors = ["vwood"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.4"
serde = "1.0.126"
serde_json = "1.0.24"
rayon = "1.3.0"
clap = "2.33.3"
